version: "3.3"
services:
  homepage:
    #image: ghcr.io/gethomepage/homepage:latest
    image: homepage_test
    build: 
    dockerfile: ../homepage/Dockerfile
    context: ../homepage/
    container_name: homepage_test
    environment:
      PUID: 1000 -- optional, your user id
      PGID: 1000 -- optional, your group id
    ports:
      - 3000:3000
    volumes:
      - ./app/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    restart: always
    labels: 
      - homepage.group=Network Management
      - homepage.name=Portainer
      - homepage.icon=portainer
      - homepage.href=http://192.168.0.106:9000
    # new labels
      - homepage.bookmarks.group1.portainer=http://192.168.0.106:9000
volumes: 
  portainer_data
