---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/docker/

my-docker:
   socket: /var/run/docker.sock
   host: 192.168.0.103
   port: 2375

# my-docker:
#   socket: /var/run/docker.sock
